export function getElements() {
  return {
    viewButtons: document.querySelectorAll('[data-view-target]'),
    views: document.querySelectorAll('.app-view'),
    healthStatus: document.querySelector('#health-status'),
    statusDot: document.querySelector('.status-dot'),
    appMessage: document.querySelector('#app-message'),
    agentCount: document.querySelector('#agent-count'),
    workflowCount: document.querySelector('#workflow-count'),
    runCount: document.querySelector('#run-count'),
    agentGrid: document.querySelector('#agent-grid'),
    workflowMap: document.querySelector('#workflow-map'),
    nodeInspector: document.querySelector('#node-inspector'),
    resetLayoutButton: document.querySelector('#reset-layout-button'),
    runsList: document.querySelector('#runs-list'),
    runForm: document.querySelector('#run-form'),
    agentForm: document.querySelector('#agent-form'),
    skillForm: document.querySelector('#skill-form'),
    workflowForm: document.querySelector('#workflow-form'),
    workflowAgentSelect: document.querySelector('#workflow-agent-select'),
    workflowAgentList: document.querySelector('#workflow-agent-list'),
    addWorkflowStepButton: document.querySelector('#add-workflow-step-button'),
    workflowStepList: document.querySelector('#workflow-step-list'),
    kbSourceForm: document.querySelector('#kb-source-form'),
    skillList: document.querySelector('#skill-list'),
    kbSourceList: document.querySelector('#kb-source-list'),
    refreshButton: document.querySelector('#refresh-button'),
    runDetail: document.querySelector('#run-detail'),
    selectedRunId: document.querySelector('#selected-run-id'),
    runActions: document.querySelector('#run-actions'),
    timeline: document.querySelector('#timeline'),
    rcaOutput: document.querySelector('#rca-output'),
    kbForm: document.querySelector('#kb-form'),
    kbResults: document.querySelector('#kb-results'),
  };
}
